### ISSUE TITLE
struo2 database of cmmg database

### ISSUE THREAD

**Issue by fconstancias** [SilasK/FunMetagenomics#1]
Hi @SilasK,

I am analyzing mice fecal metagenomes and was wondering if you would be interested in generating a [struo database](https://github.com/leylabmpi/Struo2) for cmmg? 

Best,

Florentin

**Comment by SilasK** [comment]
Good idea

**Comment by fconstancias** [comment]
Would you have time/ capacity to do that?

**Comment by SilasK** [comment]
We will do it for the next version. I can try to do it for the first version.

Have you seen the complementary approach how I get from kraken abundances to functional profiles using CMMG, described in (this notebook)[https://colab.research.google.com/github/trajkovski-lab/CMMG/blob/main/notebooks/Analyze-cold-adapted-microbiota.ipynb) . I multiply the relative abundance of each taxon quantified with Kraken or so. and multiply it with the presence/absence of  Kegg modules. also Kegg KO and CAZy are there. What do you think of this approach?


I can imagine that a Humann2 database would get you a bit fine grained results but the output should be comparable.

**Comment by fconstancias** [comment]
Hi @SilasK,

> Have you seen the complementary approach how I get from kraken abundances to functional profiles using CMMG[...]. What do you think of this approach?

I see, very relevant. I also think haveing a struo-human database would increase the resolution. 
I will follow the approach you used for now as I have limited ressources to generate the struo database. If you have time & resources for that that would be very much appreciated !

Best
